// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_data from "./routes/api/data.ts";
import * as $index from "./routes/index.tsx";
import * as $EventList from "./islands/EventList.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/data.ts": $api_data,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/EventList.tsx": $EventList,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
